dist: xenial
language: shell

services:
- docker

before_script:
- "echo commit: $TRAVIS_COMMIT"
- "echo tag: $TRAVIS_TAG"
- "echo branch: $TRAVIS_BRANCH"
- "echo build: $TRAVIS_BUILD_NUMBER"

script:
  - make all
